# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Symbid Dev Blog
subtitle: The IJburg Chronicles

<<<<<<< HEAD
disqus:
    shortname: symbidtech

google_analytics_tracking_id: UA-46751093-2

authors:
  rdohms:
      name: Rafael Dohms
      url: http://doh.ms
      twitter: http://twitter.com/rdohms
      twitter_handle: rdohms
      github: https://github.com/rdohms
      email: rafael@symbid.com
      bio: Symbid's Lead Backend Developer. Serial Creator of User Groups, speaker and contributor to PHP and its ecosystem.
