sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
        taxonomies:
            - tags
            - categories
            - authors
    jobs:
        permalink: jobs/:slug_title/
        path: _jobs
        singular_name: job
        layout: job
        enabled: true
